version: "3"
services:
  ecommerce_compra_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
      - ./start_script/startup.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: compra
      POSTGRES_USER: compra
      POSTGRES_DB: compra
    ports:
      - "5433:5432"

  ecommerce_compra_rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq_management

    ports:
      - 5672:5672 # (erlang) communication between the nodes and CLI tool
      - 15672:15672 # communication with the web management API

    volumes:
      # data persistence
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
      # data mapping -> host: container
      # queues and messages data of the container will be stored on the host
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=passw123

    restart: always

volumes:
  db-data:
    driver: local